services:
  db:
    image: postgis/postgis:15-3.3 # Official PostGIS+PostgreSQL image
    platform: linux/amd64 # Forces AMD64 emulation on ARM
    env_file: .env
    volumes:
      - postgis_data:/var/lib/postgresql/data # Persistent storage
    ports:
      - "5432:5432"  # Exposes DB to host machine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # Readiness prob
      interval: 5s
      timeout: 5s
      retries: 5

  app: # Future FastAPI service
    build: . # Uses Dockerfile in current dir
    volumes:
      - .:/app 
    ports:
      - "8000:8000" # API port
    depends_on:
      db:
        condition: service_healthy # Waits for DB readiness
    env_file: .env

volumes:
  postgis_data: # Named volume declaration