"""add_missing_fields_and_indexes

Revision ID: 61a03a65630f
Revises: 8aba0d6a3cda
Create Date: 2025-07-04 21:26:45.398026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61a03a65630f'
down_revision: Union[str, Sequence[str], None] = '8aba0d6a3cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('locations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # Create indexes
    op.create_index('idx_locations_point', 'locations', ['point'], unique=False, postgresql_using='gist')
    op.create_index('idx_locations_created_at', 'locations', ['created_at'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index('idx_locations_point', table_name='locations')
    op.drop_index('idx_locations_created_at', table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')

    # Drop columns
    op.drop_column('locations', 'updated_at')
    op.drop_column('locations', 'created_at')
    op.drop_column('locations', 'description')
    # ### end Alembic commands ###
